#!/bin/bash

# python extract_samurai.py --config /data/samurai/train_logs/navi_samurai/samurai_school_bus-n_gcp310/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
# python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_3d_dollhouse_sink-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 1, --navi_version v1.2 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_bunny_racer-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
# python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_can_kernel_corn-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.0 --dataset navi --use_test_img_id_file --force
# python extract_samurai.py --config /data/samurai/train_logs/navi_samurai/samurai_chicken_racer-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 1, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
# python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_circo_fish_toothbrush_holder_14995988-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
# python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_dino_4-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 4, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
# python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_dino_5-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 5, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
# python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_schleich_african_black_rhino-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file --force

python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_schleich_bald_eagle-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_schleich_hereford_bull-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_schleich_lion_action_figure-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_schleich_spinosaurus_action_figure-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file --force
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_school_bus-n_gcp300/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v1.2 --dataset navi --use_test_img_id_file 
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_well_with_leaf_roof_showpiece-n_gcp200/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_welcome_sign_mushrooms-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_water_gun_toy_yellow-n_gcp200/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_water_gun_toy_white-n_gcp200/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_water_gun_toy_green-n_gcp200/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_tumbler_air_balloon-n_gcp200/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_tractor_green_showpiece-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_steps_small_showpiece-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_soldier_wood_showpiece-n_gcp200/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_shoe_right_gray_s-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_remote_control_toy_car_s-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_pumpkin_showpiece_s-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_paper_weight_flowers_showpiece-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_keywest_showpiece_s-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_ice_cream_cart_showpiece-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_hut_mushrooms_showpiece-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_hand_drill_cordless_blue_black-n_gcp200/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_garbage_truck_green_toy_s-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_fire_engine_toy_red_yellow_s-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_duck_bath_yellow_s-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file
python extract_samurai.py --config /data/samurai/train_logs/navi_samurai//samurai_box_multi_door_colored-n_gcp201/args.txt --blender_path /usr/local/blender-2.93.17-stable+v293.aaedb20ff93e-linux.x86_64-release/blender --gpus 2, --navi_version v0.3 --dataset navi --use_test_img_id_file